name: CI

on: [push]

jobs:
  Install:
    name: Install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Check executables
      run: |
        ls -l -h
        test -x ./colourise
        test -x ./colour-test

    - name: colourise --help
      run: ./colourise --help

    - name: colour-test --help
      run: ./colour-test --help
