name: Rez package

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'

jobs:

  test-colourise:
    name: Can colourise in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest, macOS-latest]
        include:
            - os: ubuntu-latest
              piping: "|&"
            - os: macOS-latest
              piping: "2>&1 |"

    steps:
    - uses: actions/checkout@v1

    - name: Shotgun Log (No Terminal)
      run: cat ./tests/resources/logs/tk-desktop.log | ./colourise --shotgun-log

    - name: Katana (No Terminal)
      run: ./tests/resources/bin/katana ${{ matrix.piping }} ./colourise --katana

  test-colourise-docker-pty:
    name: Can colourise in Pseudo Docker Terminal
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Shotgun Log
      run: |
        docker run \
          --rm \
          --tty \
          -v $(pwd):/usr/local/bin:ro \
          -w /usr/local/bin centos:7 \
          bash -c 'cat ./tests/resources/logs/tk-desktop.log | ./colourise --shotgun-log'

    - name: Katana
      run: |
        docker run \
          --rm \
          --tty \
          -v $(pwd):/usr/local/bin:ro \
          -w /usr/local/bin centos:7 \
          bash -c './tests/resources/bin/katana |& ./colourise --katana'

