name: Rez package

on:
  push:
    branches-ignore: []
    #   - '**'
    # tags:
    #   - '**'

jobs:
  install-rez:
    name: Can Install in rez
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install rez and rez build --install
      shell: bash
      run: |
        set -x
        pushd $(mktemp -d)
        git clone "https://github.com/nerdvegas/rez.git" .
        python install.py
        export PATH="${PATH}:/opt/rez/bin/rez"
        mkdir -vp "$(rez config local_packages_path)"
        rez bind platform
        popd
        rez build --install
        rez view colourise
        rez env colourise -c '
          colour-test --help &&
          colourise --help &&
          ls -l $REZ_COLOURISE_ROOT'
