name: Rez package

on:
  push:
    branches-ignore: []
    #   - '**'
    # tags:
    #   - '**'

jobs:
  install-rez:
    name: Can Install in rez
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install rez and rez build --install
      shell: bash
      run: |
        pushd $(mktemp -d)
        git clone https://github.com/nerdvegas/rez.git .
        python install.py
        export PATH="${PATH}:/opt/rez/bin/rez"
        mkdir -vp "$(rez config packages_path)"
        popd
        rez build --install
        rez view colourise
