name: Rez package

on:
  push:
    branches-ignore: []
    #   - '**'
    # tags:
    #   - '**'

jobs:
  install-rez:
    name: Can Install in rez
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '2.7'

    - name: Install rez and rez build --install
      shell: bash
      run: |
        set -x
        git clone "https://github.com/nerdvegas/rez.git" .rez
        python2 -m pip install --target="_rez" .rez
        ls -l _rez/bin
        export PATH="$(pwd)/_rez/bin:${PATH}"
        rez bind rez
        mkdir -vp "$(rez config local_packages_path)"
        rez build --install
        rez view colourise
        rez env colourise -c '
          colour-test --help &&
          colourise --help &&
          ls -l $REZ_COLOURISE_ROOT'
